# Importing and creating an array

In [3]:
import numpy as np

In [6]:
a1 = np.array([1,2,3,4,5,6]) # creating an arraya1
a1

array([1, 2, 3, 4, 5, 6])

In [3]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a[1]

<IPython.core.display.Javascript object>

array([5, 6, 7, 8])

**A vector is an array with a single dimension (there’s no difference between row and column vectors), while a matrix refers to an array with two dimensions. For 3-D or higher dimensional arrays, the term tensor is also commonly used.**

axis is also called dimensions.


[[1,2,3]
[4,5,6]]         this array has two axis. first axis has a length of 2 and other has 3.

In [5]:
np.zeros(5)    # array of zeros of length 5

<IPython.core.display.Javascript object>

array([0., 0., 0., 0., 0.])

In [7]:
np.ones(5)          # array of ones of length 5

<IPython.core.display.Javascript object>

array([1., 1., 1., 1., 1.])

In [14]:
np.empty(2)                 # The function empty creates an array whose initial content is random and depends on the state of the memory

<IPython.core.display.Javascript object>

array([5.73021895e-300, 6.95286872e-310])

In [15]:
np.arange(6)  # create an array of n members, range of


<IPython.core.display.Javascript object>

array([0, 1, 2, 3, 4, 5])

In [16]:
np.arange(6, 15, 2)  # first number, last number, step size

<IPython.core.display.Javascript object>

array([ 6,  8, 10, 12, 14])

In [18]:
np.linspace(1,10, 5) # create an array with values that are spaced linearly in a specified interval: (start, end, number of elements)

<IPython.core.display.Javascript object>

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### The default data type is floating point.

In [21]:
np.ones(5, dtype=np.int64)  # specifying the datatype 

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([1, 1, 1, 1, 1])


### Sorting

np.sort(array_name, axis=-1, kind, order = none)

kind = algorithm {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}, optional


In [25]:
arr = np.array([4,6,2,5,1,8,3,9])
# arr.sort()   # sorting an array
np.sort(arr) # both are correct

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([1, 2, 3, 4, 5, 6, 8, 9])

### Concatenation

In [28]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

np.concatenate((a,b))   # double parenthesis

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
# both arrays must have double square brackets
# all are of same length 
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[9,10,11]])           
np.concatenate((x,y), axis = 0)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 9, 10, 11]])

- axis = 0, vertical in a matrix
- axis = 1, horizontal in a matrix
- axis = 2, for 3d array

### Shape and Size of array

In [47]:
# creating a three dimentional array
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

<IPython.core.display.Javascript object>

In [48]:
print(np.ndim(array_example))  # it tells the axis or dimensions of array
print(array_example.ndim)      # both methods are correct and same

<IPython.core.display.Javascript object>

3
3


In [50]:
array_example.size  # it tells the total number of elements in an array

24

In [53]:
# (int1, int2, int3), (dimensions, rows, coloumns)
array_example.shape    # output is a tuple

(3, 2, 4)

### Reshape an array

In [56]:
a = np.arange(6)
a

<IPython.core.display.Javascript object>

array([0, 1, 2, 3, 4, 5])

In [59]:
b = a.reshape(3,2)    # (length of row, length of coloumn)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [64]:
np.reshape(a, newshape=(1,6), order= 'A')

<IPython.core.display.Javascript object>

array([[0, 1, 2, 3, 4, 5]])

C means to read/write the elements using C-like index order, 

F means to read/write the elements using Fortran-like index order, 

A means to read/write the elements in Fortran-like index order if a is Fortran contiguous in memory

In [68]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

<IPython.core.display.Javascript object>

(6,)

In [70]:
a2 = a[np.newaxis, :]    # to add a new axis
a2.shape               # a has 0 dimension, while a2 has now 2 dimensions

<IPython.core.display.Javascript object>

(1, 6)

### Indexing and Slicing

In [74]:
data = np.array([1, 2, 3])
data

<IPython.core.display.Javascript object>

array([1, 2, 3])

In [80]:
print(data[1])
print(data[0:2])   # [start: number of elements]
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


In [82]:
a = np.array([[1 , 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])

<IPython.core.display.Javascript object>

**Slicing using conditional operators**

In [94]:
(a[ a < 5 ])  # printing value that are lesser than 5 in array

array([1, 2, 3, 4])

In [92]:
five_up = a[a>5]    # required output, all values stored in new variable
five_up_2 = (a>5)   # output is in true and false

print(five_up)
print(five_up_2)  # it contains false and trues of a 
print(a[five_up_2])  # it shows only true values from a


[ 6  7  8  9 10 11 12]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11 12]


In [96]:
divisble_by_2 = a[a%2==0]
divisble_by_2

array([ 2,  4,  6,  8, 10, 12])

In [99]:
c = a[(a>2) & (a<8)]
c

array([3, 4, 5, 6, 7])

In [100]:
five_up = (a > 5) | (a == 5)
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [101]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [106]:
# vertically stacking two arrays
np.vstack((a1,a2))   # double bracket must

<IPython.core.display.Javascript object>

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [107]:
# horizontally stacking two arrays
np.hstack((a1,a2)) 

<IPython.core.display.Javascript object>

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

### Splitting an array into short arrays

In [108]:
x = np.arange(1, 25).reshape(2, 12)
x

<IPython.core.display.Javascript object>

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [114]:
# splitting one array in three equally shaped short arrays
np.hsplit(x,3)

<IPython.core.display.Javascript object>

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [116]:
# specifying the coloumn number after which to cut
np.hsplit(x, (3,4))   # split array after 3rd and 4th coloumns

<IPython.core.display.Javascript object>

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

### copying an array

In [118]:
b = a.copy()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Basic Operations

In [119]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([2, 3])

In [121]:
print(data - ones)
print(data * ones)
print(data / ones)

[0 1]
[1 2]
[1. 2.]


In [124]:
a.sum()

78

In [131]:
b = np.array([[1, 1], 
              [2, 2]])

<IPython.core.display.Javascript object>

In [132]:
print(b.sum())
print(b.sum(axis = 0))  # adding vertically
print(b.sum(axis = 1))  # adding horizontally

6
[3 3]
[2 4]


In [135]:
data = np.array([1.0, 2.0, 3.0])
data * 1.6

<IPython.core.display.Javascript object>

array([1.6, 3.2, 4.8])

### Other Operations

In [137]:
print(data.max()) # telling the maximum value in the array
print(data.min()) # telling the minimum value in the array

3.0
1.0


In [139]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
print(a.min(axis=0))   # telling minimum value in each coloumn
print(a.min(axis=1))   # telling minimum value in each row

<IPython.core.display.Javascript object>

[0.12697628 0.05093587 0.26590556 0.5510652 ]
[0.17296777 0.05093587 0.12697628]


### Matrices and slicing in matrices

In [140]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

<IPython.core.display.Javascript object>

array([[1, 2],
       [3, 4],
       [5, 6]])

In [144]:
print(data[0,1])  # [row number, coloumn number]
print((data[1:3])) # printing two rows
print(data[0:2, 0]) # printing coloumn 0 of 0:2 rows

2
[[3 4]
 [5 6]]
[1 3]


In [149]:
rng = np.random.default_rng()
rng.random(3)

<IPython.core.display.Javascript object>

array([0.78235455, 0.01705389, 0.91343014])

In [151]:
rng.random((3,4))

array([[0.70112811, 0.01881664, 0.94791388, 0.89985486],
       [0.29853007, 0.84192739, 0.4123248 , 0.92439547],
       [0.05489122, 0.23180001, 0.0629642 , 0.82436376]])

In [167]:
# range and size
rng.integers(10, size=(2,4), endpoint=True) # if endpoint=False, then 10 will not be included
#by defalut 10 is not included

array([[ 1,  7,  3, 10],
       [ 5,  4,  9,  6]])

### Unique items

In [173]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
unique_values  # passes tthe unique values


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [174]:
unique_values,  indeices_list = np.unique(a, return_index=True)  # return two arrays, one if the values, 2nd is the indices
indeices_list


<IPython.core.display.Javascript object>

array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14])

In [177]:
unique_values,  occurance = np.unique(a, return_counts=True)  # return two arrays, one if the values, 2nd is the occurance
occurance


<IPython.core.display.Javascript object>

array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1])

In [178]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])


<IPython.core.display.Javascript object>

In [180]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)

print(unique_rows) # row wise unique values

print(indices)
print(occurrence_count)

<IPython.core.display.Javascript object>

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


In [185]:
print(data.transpose(), "\n")
print(data.T)

[[1 3 5]
 [2 4 6]] 

[[1 3 5]
 [2 4 6]]


In [187]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

np.flip(arr) # reverse of an array

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([8, 7, 6, 5, 4, 3, 2, 1])

In [200]:
arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)           # whole array is reversed
print(reversed_arr, "\n")
reversed_arr_rows = np.flip(arr_2d, axis=0)   # reversing the elements of each row individually, 1st row is the last row annd vice versa
print(reversed_arr_rows, "\n")


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]] 



<IPython.core.display.Javascript object>

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]] 



In [196]:
reversed_arr_coloumn = np.flip(arr_2d, axis=1)     #1st coloumn is the last coloumn and vice versa
print(reversed_arr_coloumn, "\n")


<IPython.core.display.Javascript object>

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]] 



In [201]:
# reversing the elements of a single row
arr_2d[1] = np.flip(arr_2d[1])  # 2nd row is reversed only
print(arr_2d) 

<IPython.core.display.Javascript object>

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [202]:
arr_2d[:,1] = np.flip(arr_2d[:,1])  # 2nd coloumn is reversed only
print(arr_2d) 

<IPython.core.display.Javascript object>

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [203]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()


<IPython.core.display.Javascript object>

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])