# <span style="color:red"> Libraries in python </span>

In [5]:
def calc(a, b):
    return a+b, a-b, a*b

print(calc(10,20))

(30, -10, 200)


In [8]:
import math

math.sqrt(36)

6.0

Libraries for dala analysis in python:
1. numpy
2. pandas
3. matplotlib
4. seaborn

## Importing numpy

It mainly deals with arrays and metrices(matrics) and mathematical opetions. 

In [12]:
import numpy as np # to import comlete library  
from numpy import arange  # to import a specific function from a library

## creating arrays using numpy

In [13]:
np.array([1,2,3,4,5,6]) # creating an array

array([1, 2, 3, 4, 5, 6])

In [16]:
a = np.array([1,2,3,4,5,6]) # storing the array in a variable
a

array([1, 2, 3, 4, 5, 6])

**Checking the data type of array**

In [17]:
type(a)

numpy.ndarray

[1,2,3,4,5,6]

This array has 6 columns and 1 row. This is one dimentional array. **Array that has multiple columns and single row is called one-dimensional array**

[[1,2,3,4,5,6], [7,8,9,10,11,12], [13,14,15,16,17,18]]

This array has 6 columns and 3 rows. This is two dimentional array. **Array with multiple columns and multiple rows is called two-dimensional array**

> A vector is a single dimensoinal array. 

> Array with two dimensions is called metircs. 

> 3-d arrays or higher than 3-d arrays are commonly called tensor.

> axis is also called dimension.

> Length of an array is the number of data points

In [19]:
np.zeros(5) # 5 is the length of array

array([0., 0., 0., 0., 0.])

In [20]:
np.ones(7) # array of ones with 7 length

array([1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.empty(4)

array([2.12199579e-314, 0.00000000e+000, 6.08688876e-321, 6.95208261e-310])

In [25]:
np.linspace(1,10,5)  # (start data point of array, end data point, split into 5 parts)
# 1 sy ly kr 10 tak ki array bnao, aur us ko 5 equal parts mein divide kr do. 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [29]:
np.arange(6, 16, 3) # (start, end, steps)

array([ 6,  9, 12, 15])

**The default data type is floating point.**

## specifying data type of data points

In [31]:
np.ones(5, dtype = np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

## Soting

syntax:
    
    np.sort(array_name, axis = 1, kind, order)
    kind = sorting algorithm

In [35]:
arr = np.array([3,4,1,7,32,56,89,21,34]) # creating the array
arr.sort() # sorting the array
arr # displaying

array([ 1,  3,  4,  7, 21, 32, 34, 56, 89])

In [38]:
arr = np.array([3,4,1,7,32,56,89,21,34]) # creating the array
np.sort(arr)

array([ 1,  3,  4,  7, 21, 32, 34, 56, 89])

## Concatenation

**Concatinating 1d arrays**

In [43]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
np.concatenate((b, a))

array([ 6,  7,  8,  9, 10,  1,  2,  3,  4,  5])

In [60]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
np.concatenate((a, b), axis = 0)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Concatinating 2d arrays**

In [49]:
x = np.array([[1,2,3,4,5], [6,7,8,9,10]]) 
y = np.array([[11,12,13,14,15], [16,17,18,19,20]]) 
np.concatenate((x,y), axis = 0)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [50]:
np.concatenate((x,y), axis = 1)

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [54]:
x = np.array([[1,2,3,4,5], [6,7,8,9,10]]) 
y = np.array([[11,12,13,14, 15]])
np.concatenate((x,y), axis = 0)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

1[] to make one-d array.

2[] are used to make 2-d array

3[] are used to make 3-d array

> The lenght of arrays should be same for concatenation

## Shape and Size of array


Make two dimentional arrays, and join them with a square bracket

In [63]:
# creating a three dimentional array
arr = np.array(
[
    [[0,1,2,3],
    [4,5,6,7]],
    
    [[8,9,10,11],
    [12,13,14,15]],
    
    [[16,17,18,19],
    [20,21,22,23]]
    
])

arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

Checking dimension of arrays

In [62]:
arr.ndim

3

In [64]:
np.ndim(arr)

3

Checking shape of an array

In [71]:
# checking shape of 1-d array
a = np.array([1,23,4])
a.shape # output(column)

(3,)

In [72]:
# checking shape of 2-d array
x.shape # output(ros, column)

(2, 5)

In [73]:
# checking shape of 3-d array

arr.shape # output (dimension, rows, columns)

(3, 2, 4)